# Generated by Django 4.2.7 on 2023-11-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_category_category_date_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='post_date',
            new_name='postdate',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='reading_time',
            new_name='readingtime',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_date',
            new_name='categorydate',
        ),
    ]
