# Generated by Django 4.2.7 on 2023-11-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_post_date_article_postdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
